name: Metrics
on:
  # Schedule weekly updates on Sunday
  schedule: [{cron: "0 0 * * 0"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # GitHub account and rendering configuration
          user: mkfahim
          template: classic
          config_timezone: Asia/Dhaka

          # Isometric contribution calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Programming language activity
          plugin_languages: yes

          # Notable contributions
          plugin_notable: yes
